# Render Blueprint specification: https://render.com/docs/blueprint-spec
# Defines the services that make up the InsightFlow application.

# Environment Groups (Optional but recommended for secrets)
# Define environment groups in Render dashboard and reference them here
# envVarGroups:
#  - name: supabase-secrets
#    envVars:
#      - key: SUPABASE_URL
#        value: YOUR_SUPABASE_URL_HERE
#      - key: SUPABASE_SERVICE_KEY
#        value: YOUR_SUPABASE_SERVICE_KEY_HERE
#      - key: SUPABASE_ANON_KEY
#        value: YOUR_SUPABASE_ANON_KEY_HERE

services:
  # 1. Redis Cache
  - name: insightflow-redis
    type: redis
    plan: free # Or choose a paid plan for more resources
    ipAllowList: [] # Optional: Restrict access; empty allows all Render services in the account
    maxmemoryPolicy: allkeys-lru # Example policy, choose as needed

  # 2. Backend API (FastAPI Web Service + Background Worker)
  - name: insightflow-backend
    type: web
    runtime: docker
    repo: https://github.com/Emmanuelekpeh/Insightflow # Replace with your actual repo URL
    # branch: main
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .
    plan: free # Or starter/standard depending on needs
    healthCheckPath: /health
    envVars:
      - key: SUPABASE_URL
        sync: false # Set secret in Render dashboard or use envVarGroups
      - key: SUPABASE_SERVICE_KEY
        sync: false # Set secret in Render dashboard or use envVarGroups
      - key: SENDGRID_API_KEY
        sync: false
      - key: REDIS_URL # Render provides a connection string URL for Redis
        fromService:
          type: redis
          name: insightflow-redis
          property: connectionString
      - key: REDIS_HOST # Explicit host/port needed by backend?
        fromService:
          type: redis
          name: insightflow-redis
          property: host
      - key: REDIS_PORT
        fromService:
          type: redis
          name: insightflow-redis
          property: port

  # 3. Frontend (Next.js Application)
  - name: insightflow-frontend
    type: web
    runtime: node
    repo: https://github.com/Emmanuelekpeh/Insightflow
    buildCommand: pnpm install && pnpm build
    startCommand: pnpm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: NEXT_PUBLIC_API_URL
        value: https://insightflow-backend.onrender.com # Adjust this to your backend URL 
